### ISSUE TITLE
Jupyter Notebook 0.0.3 Install Fail

### ISSUE THREAD

**Issue by jackbrucesimpson** [jupyter/atom-notebook#14]
## Version
Atom Version: 1.2.4
System: Mac OS X 10.11.1
Package version: jupyter-notebook package, v0.0.3

## Error

Installing “jupyter-notebook@0.0.3” failed.

> runas@3.1.1 install /private/var/folders/8_/10v427x95tn2p8krb08m32ch0000gn/T/apm-install-dir-115116-60845-nrzj9j/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_darwin.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/runas.node

> jupyter-js-services@0.2.1 postinstall /private/var/folders/8_/10v427x95tn2p8krb08m32ch0000gn/T/apm-install-dir-115116-60845-nrzj9j/node_modules/jupyter-notebook/node_modules/jupyter-js-services
> npm dedupe

> bufferutil@1.2.1 install /private/var/folders/8_/10v427x95tn2p8krb08m32ch0000gn/T/apm-install-dir-115116-60845-nrzj9j/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /private/var/folders/8_/10v427x95tn2p8krb08m32ch0000gn/T/apm-install-dir-115116-60845-nrzj9j/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> pathwatcher@6.3.0 install /private/var/folders/8_/10v427x95tn2p8krb08m32ch0000gn/T/apm-install-dir-115116-60845-nrzj9j/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
  CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_unix.o
  SOLINK_MODULE(target) Release/pathwatcher.node

sh: npm: command not found
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jack/.atom/.apm/.apmrc" "--userconfig" "/Users/jack/.atom/.apmrc" "install" "/private/var/folders/8_/10v427x95tn2p8krb08m32ch0000gn/T/d-115116-60845-84s5p0/package.tgz" "--target=0.34.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! jupyter-js-services@0.2.1 postinstall: `npm dedupe`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the jupyter-js-services@0.2.1 postinstall script 'npm dedupe'.
npm ERR! This is most likely a problem with the jupyter-js-services package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm dedupe
npm ERR! You can get their info via:
npm ERR!     npm owner ls jupyter-js-services
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/8_/10v427x95tn2p8krb08m32ch0000gn/T/apm-install-dir-115116-60845-nrzj9j/npm-debug.log

**Comment by gnestor** [comment]
@jackbrucesimpson Were you upgrading from a previous version?

**Comment by jackbrucesimpson** [comment]
Hi @gnestor, no, this was the first time I had installed it - I just downloaded and moved over to Atom from Sublime Text.

**Comment by gnestor** [comment]
What version of Node are you running? Atom ^1.2 upgraded to Node 4 so I think you need to have Node 4 installed to properly build packages like node-runas.

**Comment by jackbrucesimpson** [comment]
I just ran "node -v" in my terminal and got back v5.1.0 - so will I need the previous version of Node in order to run it? I've been trying to install atom-notebook from within Atom's package installer.

**Comment by gnestor** [comment]
I tested installing using Node 5.1.1 using `apm install` and inside Atom and both worked. I'm no NPM expert but it looks like apm in running its own version of Node 0.10.40 and trying to spawn `npm dedupe` as part of jupyter-js-services postinstall script:

```
sh: npm: command not found
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jack/.atom/.apm/.apmrc" "--userconfig" "/Users/jack/.atom/.apmrc" "install" "/private/var/folders/8_/10v427x95tn2p8krb08m32ch0000gn/T/d-115116-60845-84s5p0/package.tgz" "--target=0.34.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
```

The only thing I can think of is try installing Atom shell commands (Atom menu bar > Atom > Install Shell Commands) and retry.

**Comment by jackbrucesimpson** [comment]
Just gave it a go, Atom just tells me that: "The shell commands `atom` and `apm` are installed." Maybe it's a specific issue introduced on Mac in the latest version of Atom. Thank-you so much for the time you've spent helping me and for creating this package, I'll have to give it another go installing it when a new version of Atom is released that (hopefully) resolves this.

**Comment by gnestor** [comment]
Bummer. It seems like others are able to install and running into bugs elsewhere, so it sounds like you are running into some edge case. I'll keep this open and close it when you are able to install successfully. If you continue to run into problems, let us know and we will dig deeper into it.
