### ISSUE TITLE
Install Failed, 

### ISSUE THREAD

**Issue by alexkowalenko** [jupyter/atom-notebook#32]
Attempted to install the plugin for atom, but it failed. The following is the log.

> runas@3.1.1 install /private/var/folders/1q/d5rjn3_s18n7_14kf_h7f2gh0000gn/T/apm-install-dir-11611-60365-igono9/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_darwin.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/runas.node

> bufferutil@1.2.1 install /private/var/folders/1q/d5rjn3_s18n7_14kf_h7f2gh0000gn/T/apm-install-dir-11611-60365-igono9/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /private/var/folders/1q/d5rjn3_s18n7_14kf_h7f2gh0000gn/T/apm-install-dir-11611-60365-igono9/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> jupyter-js-utils@0.2.17 postinstall /private/var/folders/1q/d5rjn3_s18n7_14kf_h7f2gh0000gn/T/apm-install-dir-11611-60365-igono9/node_modules/jupyter-notebook/node_modules/jupyter-js-services/node_modules/jupyter-js-utils
> npm dedupe

> pathwatcher@6.3.1 install /private/var/folders/1q/d5rjn3_s18n7_14kf_h7f2gh0000gn/T/apm-install-dir-11611-60365-igono9/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
  CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_unix.o
  SOLINK_MODULE(target) Release/pathwatcher.node

sh: npm: command not found
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/alex/.atom/.apm/.apmrc" "--userconfig" "/Users/alex/.atom/.apmrc" "install" "/private/var/folders/1q/d5rjn3_s18n7_14kf_h7f2gh0000gn/T/d-11611-60365-1gvbub4/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! jupyter-js-utils@0.2.17 postinstall: `npm dedupe`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the jupyter-js-utils@0.2.17 postinstall script 'npm dedupe'.
npm ERR! This is most likely a problem with the jupyter-js-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm dedupe
npm ERR! You can get their info via:
npm ERR!     npm owner ls jupyter-js-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/1q/d5rjn3_s18n7_14kf_h7f2gh0000gn/T/apm-install-dir-11611-60365-igono9/npm-debug.log

**Comment by johnxllis** [comment]
Same issue here on both OS X El Captian and Ubuntu 14.04.

**Comment by gnestor** [comment]
Try `PYTHON=python2 apm install`

**Comment by kfix** [comment]
Atom 1.5.3 on OSX 10.11.3

```
$ apm -v
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.0

$ apm install jupyter-notebook
Installing jupyter-notebook to /Users/jkorkames/.atom/packages ✗

> runas@3.1.1 install /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_darwin.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/runas.node

> bufferutil@1.2.1 install /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> jupyter-js-utils@0.3.2 postinstall /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/jupyter-js-services/node_modules/jupyter-js-utils
> npm dedupe


> pathwatcher@6.3.1 install /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
  CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_unix.o
  SOLINK_MODULE(target) Release/pathwatcher.node

> jupyter-js-services@0.5.1 postinstall /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/jupyter-js-services
> npm dedupe

minimist@1.2.0 node_modules/jupyter-js-utils/node_modules/minimist -> node_modules/minimist
requirejs@2.1.22 node_modules/jupyter-js-utils/node_modules/requirejs -> node_modules/requirejs

npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "dedupe"
npm ERR! node v0.10.40
npm ERR! npm  v3.5.3
npm ERR! path /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/jupyter-js-services/node_modules/jupyter-js-utils/node_modules/.bin/r.js
npm ERR! code EEXIST

npm ERR! Refusing to delete /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/jupyter-js-services/node_modules/jupyter-js-utils/node_modules/.bin/r.js: containing path /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/jupyter-js-services/node_modules/jupyter-js-utils/node_modules/requirejs isn't under npm's control
npm ERR! File exists: /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/jupyter-js-services/node_modules/jupyter-js-utils/node_modules/.bin/r.js
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/jupyter-js-services/npm-debug.log
npm ERR! Darwin 15.3.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jkorkames/.atom/.apm/.apmrc" "--userconfig" "/Users/jkorkames/.atom/.apmrc" "install" "/private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/d-116116-9700-ksanl3/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! jupyter-js-services@0.5.1 postinstall: `npm dedupe`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jupyter-js-services@0.5.1 postinstall script 'npm dedupe'.
npm ERR! This is most likely a problem with the jupyter-js-services package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm dedupe
npm ERR! You can get their info via:
npm ERR!     npm owner ls jupyter-js-services
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/npm-debug.log```

**Comment by kfix** [comment]
& from within Atom's installer:
```
> runas@3.1.1 install /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-8859-wynld/node_modules/jupyter-notebook/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_darwin.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/runas.node

> utf-8-validate@1.2.1 install /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-8859-wynld/node_modules/jupyter-notebook/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> bufferutil@1.2.1 install /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-8859-wynld/node_modules/jupyter-notebook/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> jupyter-js-utils@0.3.2 postinstall /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-8859-wynld/node_modules/jupyter-notebook/node_modules/jupyter-js-services/node_modules/jupyter-js-utils
> npm dedupe


> pathwatcher@6.3.1 install /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-8859-wynld/node_modules/jupyter-notebook/node_modules/pathwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
  CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_unix.o
  SOLINK_MODULE(target) Release/pathwatcher.node

sh: npm: command not found
npm ERR! Darwin 15.3.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom/1.0.2/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jkorkames/.atom/.apm/.apmrc" "--userconfig" "/Users/jkorkames/.atom/.apmrc" "install" "/private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/d-116116-8859-xbypvv/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! jupyter-js-utils@0.3.2 postinstall: `npm dedupe`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the jupyter-js-utils@0.3.2 postinstall script 'npm dedupe'.
npm ERR! This is most likely a problem with the jupyter-js-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm dedupe
npm ERR! You can get their info via:
npm ERR!     npm owner ls jupyter-js-utils
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-8859-wynld/npm-debug.log
```

**Comment by gnestor** [comment]
This looks like a relevant line: 

```
npm ERR! File exists: /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/jupyter-js-services/node_modules/jupyter-js-utils/node_modules/.bin/r.js
npm ERR! Move it away, and try again.
```

Try removing that file using `rm /private/var/folders/m8/l0gl08bj0zn4zpck62hn3yv40000gp/T/apm-install-dir-116116-9700-1f2m3ac/node_modules/jupyter-notebook/node_modules/jupyter-js-services/node_modules/jupyter-js-utils/node_modules/.bin/r.js` and reinstalling. 

If that doesn't work, we should probably open an issue on jupyter-js-utils: `npm ERR! Failed at the jupyter-js-utils@0.3.2 postinstall script 'npm dedupe'.`

**Comment by kfix** [comment]
the /tmp folder is created and destroyed with each `apm install` run, nothing I can clean up for it.
npm v2 is so old that I'm not surprised that npm-dedupe is being buggy. its a :imp: move for jupyter-js-utils's postinstall to use it, but maybe atom/apm should [upgrade](https://github.com/atom/apm/issues/436) its npm.

**Comment by rgbkrk** [comment]
> its a :imp: move for jupyter-js-utils's postinstall to use it

Agreed.

**Comment by blink1073** [comment]
This looks like a permissions issue, where `npm dedupe` isn't being allowed to run properly.  We are using `npm dedupe` specifically to overcome limitations in `npm` resolution logic in older versions.

**Comment by kfix** [comment]
I used `TMPDIR=~/.atom/.apm-tmp apm install jupyter-notebook` to try and get better perms. no change.
additionally, all the debug logs still get blown away from that TMPDIR. npm's log dir is completely [unconfigurable](https://github.com/npm/npm/issues/1548).
@blink1073 what are the limitations that dedupe is being utilized to work around?

**Comment by blink1073** [comment]
Dedupe avoids having duplicate versions of libraries in node_modules, and is a standard npm command.

**Comment by rgbkrk** [comment]
While `npm dedupe` saves disk space, it is currently causing friction with users. Putting commands in postinstall tends to be bad practice for userland as well.

Options:

1. Rely on peer dependencies. End user applications have to list these peer deps within their primary dependencies.

2. Use dedupe only at the stage of live code/user space (server, command line tool, stitched together front end).

3. Use a different package that doesn't bother with the dedupe.

**Comment by blink1073** [comment]
@rgbkrk, the reason we need dedupe is not to save disk space, but to ensure that `isinstance Foo` works, which is not the case if you have different versions of the same library loaded with different versions of the same class.

**Comment by rgbkrk** [comment]
Oh, ok. Peer deps would be the idiomatic and safe way of handling that then.

**Comment by blink1073** [comment]
Thanks Kyle, I'll give that a try on Monday.

**Comment by Ken0sis** [comment]
I just tried to install this package and having the same error.  This package looks great, and hope next update will address issue.

**Comment by blink1073** [comment]
I released `jupyter-js-utils@0.3.3`, which avoids `npm dedupe`.

**Comment by Ken0sis** [comment]
Thank you for the update. It fixed the problem and allowed me to install.  I just can't get it to open .ipynb files right now because it keeps complaining about not having jupyter session (which I did run from terminal).  Probably just something on my end and I need to learn how this jupyter package works.

Thanks again for the work on update!

**Comment by gnestor** [comment]
Now you need to make sure that the path to your Jupyter binary is in Atom's
path or in the jupyter-notebook settings. The package will run an instance
of Jupyter Kernel Gateway for you.

**Comment by kfix** [comment]
jupyter-notebook Installs and runs for me now. Thanks @blink1073 @rgbkrk @gnestor !

**Comment by gnestor** [comment]
Good news! 👍👍
