### ISSUE TITLE
Cant install on Windows

### ISSUE THREAD

**Issue by ahmadmustafaanis** [jupyter/atom-notebook#96]
I just installed Atom and this is the error log

`> bufferutil@1.2.1 install C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\node_modules\jupyter-notebook\node_modules\bufferutil
> node-gyp rebuild

C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\node_modules\jupyter-notebook\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> utf-8-validate@1.2.2 install C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\node_modules\jupyter-notebook\node_modules\utf-8-validate
> node-gyp rebuild

C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\node_modules\jupyter-notebook\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> pathwatcher@8.1.0 install C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\node_modules\jupyter-notebook\node_modules\pathwatcher
> node-gyp rebuild

C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\node_modules\jupyter-notebook\node_modules\pathwatcher>if not defined npm_config_node_gyp (node "C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "F:\Anaconda\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\Ahmad Anis\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ahmad Anis\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\node_modules\jupyter-notebook\node_modules\bufferutil
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "F:\Anaconda\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\Ahmad Anis\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ahmad Anis\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\node_modules\jupyter-notebook\node_modules\utf-8-validate
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "F:\Anaconda\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Ahmad Anis\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\Ahmad Anis\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ahmad Anis\\AppData\\Local\\atom\\app-1.43.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\node_modules\jupyter-notebook\node_modules\pathwatcher
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\AHMADA~1\AppData\Local\Temp\apm-install-dir-12015-13416-dmexj2.8cdvw\package.json'
npm WARN apm-install-dir-12015-13416-dmexj2.8cdvw No description
npm WARN apm-install-dir-12015-13416-dmexj2.8cdvw No repository field.
npm WARN apm-install-dir-12015-13416-dmexj2.8cdvw No README data
npm WARN apm-install-dir-12015-13416-dmexj2.8cdvw No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\jupyter-notebook\node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules\jupyter-notebook\node_modules\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ahmad Anis\.atom\.apm\_logs\2020-02-05T05_45_42_777Z-debug.log`

**Comment by kerajel** [comment]
Same here

**Comment by mohcineelharras** [comment]
Same here

**Comment by lucas7lima** [comment]
So, how did you solve this issue? I'm having the same error, as it appears :|

**Comment by kerajel** [comment]
> 
> 
> So, how did you solve this issue? I'm having the same error, as it appears :|

Quite easily in fact: I switched from Atom to VS Code
